name: web
channels:
  - bioconda
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - altair=5.0.1
  - anarci=2021.02.04
  - arrow-cpp=11.0.0
  - asttokens=2.0.5
  - attrs=23.1.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - blas=1.0
  - blinker=1.4
  - boost-cpp=1.73.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - cachetools=4.2.2
  - certifi=2023.7.22
  - cffi=1.15.1
  - click=8.0.4
  - comm=0.1.2
  - cryptography=41.0.3
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - freetype=2.12.1
  - gflags=2.2.2
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.30
  - glog=0.5.0
  - grpc-cpp=1.48.2
  - hmmer=3.3.2
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - intel-openmp=2021.4.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - jupyterlab_widgets=3.0.5
  - keras-preprocessing=1.1.2
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.2.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.52.0
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1w
  - orc=1.7.4
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pooch=1.7.0
  - prompt-toolkit=3.0.36
  - protobuf=3.20.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pycparser=2.21
  - pygments=2.15.1
  - pympler=0.9
  - pyopenssl=23.2.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - pyyaml=6.0
  - pyzmq=25.1.0
  - re2=2022.04.01
  - readline=8.2
  - requests=2.31.0
  - rich=13.3.5
  - scipy=1.10.1
  - setuptools=65.6.3
  - six=1.16.0
  - smmap=4.0.0
  - snappy=1.1.9
  - sqlite=3.40.1
  - stack_data=0.2.0
  - tenacity=8.2.2
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.3.2
  - traitlets=5.7.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2022a
  - tzlocal=2.1
  - utf8proc=2.6.1
  - validators=0.18.2
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - wheel=0.37.1
  - widgetsnbextension=4.0.5
  - xz=5.2.10
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - astunparse==1.6.3
      - biopython==1.81
      - biothings-client==0.3.0
      - chardet==5.2.0
      - charset-normalizer==3.3.0
      - flatbuffers==23.5.26
      - gast==0.5.4
      - google-auth==2.23.2
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - gprofiler-official==1.0.0
      - grpcio==1.59.0
      - h5py==3.9.0
      - keras==2.14.0
      - libclang==16.0.6
      - markdown==3.4.4
      - ml-dtypes==0.2.0
      - mygene==3.2.2
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==23.2
      - pandas==2.1.1
      - pip==23.2.1
      - platformdirs==3.11.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydeck==0.8.1b0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - streamlit==1.27.1
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.1
      - tensorflow==2.14.0
      - tensorflow-estimator==2.14.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.3.0
      - tqdm==4.66.1
      - urllib3==2.0.6
      - werkzeug==3.0.0
      - wrapt==1.14.1
